# Project-BI

###
# @name index.html
GET http://localhost:3000/index.html

###
# @name databaseJSON
GET http://localhost:3000/databaseJSON

###
# @name doesntExist
GET http://localhost:3000/doesntExist
